services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: go-backend
    # depends_on:
    #   - postgres
    #   - parsing
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_URL=${APP_URL}
      - APP_PORT=${APP_PORT}
      - APP_KEY=${APP_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PARSING_SERVICE_HOST=${PARSING_SERVICE_HOST}
      - PARSING_SERVICE_PORT=${PARSING_SERVICE_PORT}
    volumes:
      - ./backend:/app

  # parsing:
  #   build: ./parsing
  #   container_name: python-parsing
  #   working_dir: /scripts
  #   volumes:
  #     - ./parsing:/app
  #   command: ["python", "main.py"]
  #   ports:
  #     - "${PARSING_SERVICE_PORT}:${PARSING_SERVICE_PORT}"
  #
  # postgres:
  #   image: postgres:14
  #   container_name: postgres-db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "${DB_PORT}:${DB_PORT}"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./database:/docker-entrypoint-initdb.d
# volumes:
#   postgres_data:
