START_BOOK = ["Genesis", "Genèse"]       # livres possibles pour le début
END_BOOK   = ["Revelation", "Apocalypse"] # livres possibles pour la fin
BOOKS_EN = [
    # Pentateuque
    "Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy",
    # Historiques
    "Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings", "2 Kings",
    "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah", "Tobit", "Judith",
    "Esther", "1 Maccabees", "2 Maccabees",
    # Poétiques
    "Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Songs", "Wisdom of Solomon",
    "Sirach",
    # Prophétiques
    "Isaiah", "Jeremiah", "Lamentations", "Baruch", "Ezekiel", "Daniel", "Hosea",
    "Joel", "Amos", "Obadiah", "Jonah", "Micah", "Nahum", "Habakkuk", "Zephaniah",
    "Haggai", "Zechariah", "Malachi",
    # NT
    "Matthew", "Mark", "Luke", "John", "Acts", "Romans", "1 Corinthians", "2 Corinthians",
    "Galatians", "Ephesians", "Philippians", "Colossians", "1 Thessalonians",
    "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus", "Philemon", "Hebrews",
    "James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John", "Jude", "Revelation"
]

BOOKS_FR = [
    # Pentateuque
    "Genèse", "Exode", "Lévitique", "Nombres", "Deutéronome",
    # Historiques
    "Josué", "Juges", "Ruth", "1 Samuel", "2 Samuel", "1 Rois", "2 Rois",
    "1 Chroniques", "2 Chroniques", "Esdras", "Néhémie", "Tobie", "Judith",
    "Esther", "1 Maccabées", "2 Maccabées",
    # Poétiques
    "Job", "Psaumes","Psaume" ,"Proverbes", "Ecclésiaste", "Cantique des Cantiques",
    "Cantique","Sagesse", "Siracide",
    # Prophétiques
    "Isaïe", "Esaïe","Jérémie", "Lamentations", "Baruch", "Ézéchiel", "Ezéchiel","Daniel", "Osée",
    "Joël", "Amos", "Abdias", "Jonas", "Michée", "Nahum", "Habacuc", "Sophonie",
    "Aggée", "Zacharie", "Malachie",
    # NT
    "Matthieu", "Marc", "Luc", "Jean", "Actes", "Romains", "1 Corinthiens", "2 Corinthiens",
    "Galates",  "Ephésiens","Éphésiens", "Philippiens", "Colossiens", "1 Thessaloniciens",
    "2 Thessaloniciens", "1 Timothée", "2 Timothée", "Tite", "Philémon", "Hébreux",
    "Jacques", "1 Pierre", "2 Pierre", "1 Jean", "2 Jean", "3 Jean", "Jude", "Apocalypse"
]

FRENCH_TO_ENGLISH = {
    "Genèse": "Genesis",
    "Genese": "Genesis",
    "Génèse": "Genesis",
    "Exode": "Exodus",
    "Lévitique": "Leviticus",
    "Levitique": "Leviticus",
    "Nombres": "Numbers",
    "Deutéronome": "Deuteronomy",
    "Josué": "Joshua",
    "Juges": "Judges",
    "Ruth": "Ruth",
    "1 Samuel": "1 Samuel",
    "2 Samuel": "2 Samuel",
    "1 Rois": "1 Kings",
    "2 Rois": "2 Kings",
    "1 Chroniques": "1 Chronicles",
    "2 Chroniques": "2 Chronicles",
    "Esdras": "Ezra",
    "Néhémie": "Nehemiah",
    "Nehemie": "Nehemiah",
    "Tobie": "Tobit",
    "Judith": "Judith",
    "Esther": "Esther",
    "1 Maccabées": "1 Maccabees",
    "1 Maccabees": "1 Maccabees",
    "2 Maccabées": "2 Maccabees",
    "2 Maccabees": "2 Maccabees",
    "Job": "Job",
    "Psaumes": "Psalms",
    "Psaume": "Psalms",
    "Proverbes": "Proverbs",
    "Ecclésiaste": "Ecclesiastes",
    "Ecclesiaste": "Ecclesiastes",
    "Cantique des Cantiques": "Song of Solomon",
    "Cantique": "Song of Solomon",
    "Sagesse": "Wisdom of Solomon",
    "Siracide": "Sirach",
    "Isaïe": "Isaiah",
    "Esaïe": "Isaiah",
    "Ésaïe": "Isaiah",
    "Jérémie": "Jeremiah",
    "Lamentations": "Lamentations",
    "Baruch": "Baruch",
    "Ézéchiel": "Ezekiel",
    "Ezéchiel": "Ezekiel",
    "Ezechiel": "Ezekiel",
    "Daniel": "Daniel",
    "Osée": "Hosea",
    "Joël": "Joel",
    "Joel": "Joel",
    "Amos": "Amos",
    "Abdias": "Obadiah",
    "Jonas": "Jonah",
    "Michée": "Micah",
    "Nahum": "Nahum",
    "Habacuc": "Habakkuk",
    "Sophonie": "Zephaniah",
    "Aggée": "Haggai",
    "Zacharie": "Zechariah",
    "Malachie": "Malachi",
    "Matthieu": "Matthew",
    "Marc": "Mark",
    "Luc": "Luke",
    "Jean": "John",
    "Actes": "Acts",
    "Romains": "Romans",
    "1 Corinthiens": "1 Corinthians",
    "2 Corinthiens": "2 Corinthians",
    "Galates": "Galatians",
    "Éphésiens": "Ephesians",
    "Ephésiens": "Ephesians",
    "Ephesiens": "Ephesians",
    "Éphesiens": "Ephesians",
    "Philippiens": "Philippians",
    "Colossiens": "Colossians",
    "1 Thessaloniciens": "1 Thessalonians",
    "2 Thessaloniciens": "2 Thessalonians",
    "1 Timothée": "1 Timothy",
    "1 Timothee": "1 Timothy",
    "2 Timothee": "2 Timothy",
    "2 Timothée": "2 Timothy",
    "Tite": "Titus",
    "Philémon": "Philemon",
    "Philemon": "Philemon",
    "Hébreux": "Hebrews",
    "Hebreux": "Hebrews",
    "Jacques": "James",
    "1 Pierre": "1 Peter",
    "2 Pierre": "2 Peter",
    "1 Jean": "1 John",
    "2 Jean": "2 John",
    "3 Jean": "3 John",
    "Jude": "Jude",
    "Apocalypse": "Revelation"
}


SEED_BOOKS = [
    # Old Testament
    {"title": "Genesis",          "abbreviation": "Gen",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Exodus",           "abbreviation": "Exod", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Leviticus",        "abbreviation": "Lev",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Numbers",          "abbreviation": "Num",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Deuteronomy",      "abbreviation": "Deut", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Joshua",           "abbreviation": "Josh", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Judges",           "abbreviation": "Judg", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Ruth",             "abbreviation": "Ruth", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "1 Samuel",         "abbreviation": "1 Sam","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "2 Samuel",         "abbreviation": "2 Sam","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "1 Kings",          "abbreviation": "1 Kgs","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "2 Kings",          "abbreviation": "2 Kgs","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "1 Chronicles",     "abbreviation": "1 Chr","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "2 Chronicles",     "abbreviation": "2 Chr","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Ezra",             "abbreviation": "Ezra", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Nehemiah",         "abbreviation": "Neh",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Tobit",         "abbreviation": "Tobit",  "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Judith",         "abbreviation": "Judith",  "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Esther",           "abbreviation": "Est",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "1 Maccabees",           "abbreviation": "1 Macc",  "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "2 Maccabees",           "abbreviation": "2 Macc",  "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Job",              "abbreviation": "Job",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Psalms",           "abbreviation": "Ps",   "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Proverbs",         "abbreviation": "Prov", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Ecclesiastes",     "abbreviation": "Eccl", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Songs of Songs",  "abbreviation": "Song", "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Wisdom of Solomon",  "abbreviation": "Wisd", "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Sirach",  "abbreviation": "Sir", "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Isaiah",           "abbreviation": "Isa",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Jeremiah",         "abbreviation": "Jer",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Lamentations",     "abbreviation": "Lam",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Baruch",     "abbreviation": "Baru",  "is_deuterocanonical": 1, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Ezekiel",          "abbreviation": "Ezek", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Daniel",           "abbreviation": "Dan",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Hosea",            "abbreviation": "Hos",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Joel",             "abbreviation": "Joel", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Amos",             "abbreviation": "Amos", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Obadiah",          "abbreviation": "Obad", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Jonah",            "abbreviation": "Jonah","is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Micah",            "abbreviation": "Mic",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Nahum",            "abbreviation": "Nah",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Habakkuk",         "abbreviation": "Hab",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Zephaniah",        "abbreviation": "Zeph", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Haggai",           "abbreviation": "Hag",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Zechariah",        "abbreviation": "Zech", "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},
    {"title": "Malachi",          "abbreviation": "Mal",  "is_deuterocanonical": 0, "is_old_testament": 1, "is_new_testament": 0},

    # New Testament
    {"title": "Matthew",          "abbreviation": "Matt", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Mark",             "abbreviation": "Mark", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Luke",             "abbreviation": "Luke", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "John",             "abbreviation": "John", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Acts",             "abbreviation": "Acts", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Romans",           "abbreviation": "Rom",  "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "1 Corinthians",    "abbreviation": "1 Cor","is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "2 Corinthians",    "abbreviation": "2 Cor","is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Galatians",        "abbreviation": "Gal",  "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Ephesians",        "abbreviation": "Eph",  "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Philippians",      "abbreviation": "Phil", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Colossians",       "abbreviation": "Col",  "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "1 Thessalonians",  "abbreviation": "1 Thess", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "2 Thessalonians",  "abbreviation": "2 Thess", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "1 Timothy",        "abbreviation": "1 Tim", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "2 Timothy",        "abbreviation": "2 Tim", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Titus",            "abbreviation": "Titus", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Philemon",         "abbreviation": "Philem", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Hebrews",          "abbreviation": "Heb", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "James",            "abbreviation": "Jas", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "1 Peter",          "abbreviation": "1 Pet", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "2 Peter",          "abbreviation": "2 Pet", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "1 John",           "abbreviation": "1 Jn", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "2 John",           "abbreviation": "2 Jn", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "3 John",           "abbreviation": "3 Jn", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Jude",             "abbreviation": "Jude", "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1},
    {"title": "Revelation",       "abbreviation": "Rev",  "is_deuterocanonical": 0, "is_old_testament": 0, "is_new_testament": 1}
]
